---
- name: Converge
  hosts: instance
  become: true
  vars:
    step_ca_client_url: https://step-ca:9000
    step_ca_client_fingerprint: "{{ step_ca_fingerprint.stdout | trim }}"
    step_ca_client_provisioner_password: molecule-password
  pre_tasks:
    - name: Read the ephemeral CA's root fingerprint
      ansible.builtin.raw: step certificate fingerprint /home/step/certs/root_ca.crt
      delegate_to: step-ca
      become: false
      register: step_ca_fingerprint
      changed_when: false

  tasks:
    - name: Include role for first domain
      ansible.builtin.include_role:
        name: robertyoung.step_ca_client
      vars:
        step_ca_client_cert_name: molecule-test.local
        step_ca_client_post_renew_commands:
          - "/usr/bin/touch /tmp/cert-renewed-marker-first"

    - name: Include role for second domain
      ansible.builtin.include_role:
        name: robertyoung.step_ca_client
      vars:
        step_ca_client_cert_name: second-domain.local
        step_ca_client_post_renew_commands:
          - "/usr/bin/touch /tmp/cert-renewed-marker-second"
