---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: step-ca
    image: smallstep/step-ca:0.30.2
    override_command: false
    pre_build_image: true
    env:
      DOCKER_STEPCA_INIT_NAME: Molecule
      DOCKER_STEPCA_INIT_DNS_NAMES: step-ca
      DOCKER_STEPCA_INIT_PROVISIONER_NAME: ansible
      DOCKER_STEPCA_INIT_PASSWORD: molecule-password
    networks:
      - name: molecule-step-ca
  - name: instance
    image: geerlingguy/docker-debian13-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    networks:
      - name: molecule-step-ca

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml

verifier:
  name: ansible
